"""Console script for myah-hermes-plugin.

Provides::

    myah-hermes-plugin install --dashboard-only --target <DIR>

Materializes the discovery hook for the myah-admin dashboard plugin at
``<DIR>/myah-admin/dashboard/`` so Hermes' filesystem dashboard discovery
(``hermes_cli/web_server.py:_discover_dashboard_plugins``) can find it.

Approach (Phase 4e — Approach A):
    The actual dashboard router lives inside the pip-installed
    ``myah_hermes_plugin.myah_admin.dashboard.plugin_api`` module, where
    it can use clean relative imports. The materialized files are
    therefore minimal:

      * ``manifest.json`` — copied verbatim from package data so Hermes'
        scanner sees the plugin.
      * ``plugin_api.py`` — a one-import shim that pulls ``router`` from
        the pip package. Hermes' loader does
        ``importlib.util.spec_from_file_location`` on this file (no
        ``submodule_search_locations``), so the shim must use an absolute
        import; because ``myah_hermes_plugin`` is on ``sys.path`` after
        ``pip install``, that resolves cleanly.

    None of the sub-router files are materialized — they live exclusively
    inside the pip package as a single source of truth. That sidesteps
    the ``_load_sibling()`` gymnastics the legacy ``plugins/myah-admin/``
    layout needed to work around the package-less load.

Why a CLI instead of ``register(ctx)``:
    Hermes' dashboard discovery is filesystem-only — there is no
    entry-point group for dashboard plugins as of upstream tip 2026-05-06
    (``register_dashboard_plugin`` does not exist in
    ``hermes_cli/plugins.py``). The general ``hermes_agent.plugins``
    entry point that the rest of this package uses targets tools / hooks
    / CLI commands, not dashboard FastAPI routers. The filesystem path
    is upstream-supported and keeps the runtime discovery model
    identical pre/post Phase 4e.

Why bake at build time, not at container spawn:
    Variable network latency to PyPI + plugin version skew between
    containers + rollback complexity. Image SHA == plugin version =>
    atomic rollback. The Dockerfile invokes this CLI at image build
    time, populating ``/opt/myah/plugins/myah-admin/``; the entrypoint
    symlinks that into ``${HERMES_HOME}/plugins/myah-admin/`` at every
    container start, so the dashboard is available the moment the
    process boots.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from importlib import resources
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Filesystem-discovery shim for myah-admin dashboard plugin.
#
# Generated verbatim into ``<target>/myah-admin/dashboard/plugin_api.py`` by
# the install command. Hermes' dashboard loader reads it via
# ``importlib.util.spec_from_file_location``, so it can only contain
# absolute imports — relative imports (``from .``) raise at load time
# because the loader does not set ``submodule_search_locations``.
# ─────────────────────────────────────────────────────────────────────────────

_PLUGIN_API_SHIM = '''\
"""Filesystem-discovery shim for myah-admin dashboard plugin.

Generated by ``myah-hermes-plugin install --dashboard-only``.

The real plugin code lives in the pip-installed
``myah_hermes_plugin.myah_admin.dashboard.plugin_api`` module; this file is
just the discovery hook for Hermes' filesystem dashboard scanner
(``hermes_cli/web_server.py:_discover_dashboard_plugins``).
"""

from myah_hermes_plugin.myah_admin.dashboard.plugin_api import router

__all__ = ["router"]
'''


def _copy_dashboard(target_dir: Path) -> int:
    """Materialize the myah-admin discovery hook at ``<target_dir>/myah-admin/``.

    Writes::

        <target_dir>/myah-admin/dashboard/manifest.json   (copied from package data)
        <target_dir>/myah-admin/dashboard/plugin_api.py   (one-import shim)

    Returns 0 on success, non-zero on error. Idempotent — re-running
    overwrites both files.
    """
    dest_root = target_dir / 'myah-admin'
    dest_dashboard = dest_root / 'dashboard'
    dest_dashboard.mkdir(parents=True, exist_ok=True)

    try:
        # Copy manifest.json from package data. ``as_file`` is needed
        # because the package may live inside a wheel/zip.
        with resources.as_file(
            resources.files('myah_hermes_plugin.myah_admin.dashboard') / 'manifest.json'
        ) as manifest_src:
            shutil.copy2(manifest_src, dest_dashboard / 'manifest.json')

        # Write the import-shim. We materialize this verbatim instead of
        # copying from package data so the shim can never accidentally
        # bring sub-router source files along — those must live only in
        # the pip package.
        (dest_dashboard / 'plugin_api.py').write_text(_PLUGIN_API_SHIM, encoding='utf-8')
    except Exception as exc:
        print(f'ERROR: failed to install dashboard plugin: {exc}', file=sys.stderr)
        return 1

    print(f'Installed myah-admin dashboard plugin at {dest_root}')
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog='myah-hermes-plugin',
        description='Install/manage the Myah Hermes plugin filesystem-discoverable assets.',
    )
    sub = parser.add_subparsers(dest='cmd', required=True)

    install = sub.add_parser(
        'install',
        help='Materialize plugin assets at a filesystem location Hermes can discover.',
    )
    install.add_argument(
        '--dashboard-only',
        action='store_true',
        help='Install only the dashboard plugin (skip future tool/skill installs).',
    )
    install.add_argument(
        '--target',
        type=Path,
        required=True,
        help='Target directory (e.g. /opt/myah/plugins/ or ~/.hermes/plugins/).',
    )

    args = parser.parse_args(argv)

    if args.cmd == 'install':
        if not args.dashboard_only:
            print(
                'ERROR: only --dashboard-only is supported in this version. '
                'Future versions may install tools/skills/etc.',
                file=sys.stderr,
            )
            return 2
        return _copy_dashboard(args.target)

    return 2


if __name__ == '__main__':
    sys.exit(main())
